"""update User table -> passsword nullable

Revision ID: 4716ebbca85c
Revises: f0d6b01e532d
Create Date: 2025-03-31 19:20:02.114511

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4716ebbca85c"
down_revision: Union[str, None] = "f0d6b01e532d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "userprofile",
        "password_hash",
        existing_type=sa.VARCHAR(length=100),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "userprofile",
        "password_hash",
        existing_type=sa.VARCHAR(length=100),
        nullable=False,
    )
    # ### end Alembic commands ###
