"""add indexes on email, username

Revision ID: f0d6b01e532d
Revises: 99e29b5ed74f
Create Date: 2025-03-31 05:26:28.762075

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f0d6b01e532d"
down_revision: Union[str, None] = "99e29b5ed74f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("userprofile_email_key", "userprofile", type_="unique")
    op.drop_constraint(
        "userprofile_username_key", "userprofile", type_="unique"
    )
    op.create_index(
        op.f("ix_userprofile_email"), "userprofile", ["email"], unique=True
    )
    op.create_index(
        op.f("ix_userprofile_username"),
        "userprofile",
        ["username"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_userprofile_username"), table_name="userprofile")
    op.drop_index(op.f("ix_userprofile_email"), table_name="userprofile")
    op.create_unique_constraint(
        "userprofile_username_key", "userprofile", ["username"]
    )
    op.create_unique_constraint(
        "userprofile_email_key", "userprofile", ["email"]
    )
    # ### end Alembic commands ###
